### ISSUE TITLE
runtime: out of memory: cannot allocate 243269632-byte block (1392377856 in use) fatal error: out of memory

### ISSUE THREAD

**Issue by tpsmr** [asticode/go-astilectron-demo#77]
2022/02/19 21:48:33 Running rsrc for icon C:\Program Files\go\gopath\src\github.com\asticode\go-astilectron-demo\resources\icon.ico into C:\Program Files\go\gopath\src\github.com\asticode\go-astilectron-demo\windows.syso
2022/02/19 21:48:33 Removing C:\Program Files\go\gopath\src\github.com\asticode\go-astilectron-demo\output\windows-386
2022/02/19 21:48:33 Creating C:\Program Files\go\gopath\src\github.com\asticode\go-astilectron-demo\output\windows-386
2022/02/19 21:48:33 Building for os windows and arch 386 astilectron: 0.51.0 electron: 11.4.3
2022/02/19 21:48:33 Executing go build -ldflags -H "windowsgui" -X "main.AppName=Astilectron demo" -X "main.BuiltAt=2022-02-19 21:48:33.6225871 +0800 CST m=+8.622519101" -X "main.VersionAstilectron=0.51.0" -X "main.VersionElectron=11.4.3" -o C:\Program Files\go\gopath\src\github.com\asticode\go-astilectron-demo\output\windows-386\binary github.com\asticode\go-astilectron-demo
2022/02/19 21:48:53 bundling failed: bundling for environment windows/386 failed: building failed: # github.com/asticode/go-astilectron-demo
runtime: out of memory: cannot allocate 243269632-byte block (1392377856 in use)
fatal error: out of memory

**Comment by tpsmr** [comment]
goroutine 6 [running]:
runtime.throw(0xdc08ed, 0xd)
        c:/go/src/runtime/panic.go:1117 +0x64 fp=0x12861aec sp=0x12861ad8 pc=0x665354
runtime.(*mcache).allocLarge(0x2200088, 0xe700000, 0x12890101, 0x128900f8)
        c:/go/src/runtime/mcache.go:226 +0x250 fp=0x12861b1c sp=0x12861aec pc=0x644a40
runtime.mallocgc(0xe700000, 0xd658e0, 0xdb00001, 0x6eaaa3)
        c:/go/src/runtime/malloc.go:1078 +0x738 fp=0x12861b64 sp=0x12861b1c pc=0x63be28
runtime.makeslice(0xd658e0, 0xe700000, 0xe700000, 0x100001)
        c:/go/src/runtime/slice.go:98 +0x4f fp=0x12861b78 sp=0x12861b64 pc=0x679ccf
cmd/compile/internal/syntax.(*source).fill(0x12892010)
        c:/go/src/cmd/compile/internal/syntax/source.go:180 +0x9f fp=0x12861bac sp=0x12861b78 pc=0x74f8af
cmd/compile/internal/syntax.(*source).nextch(0x12892010)
        c:/go/src/cmd/compile/internal/syntax/source.go:134 +0x2e fp=0x12861bd4 sp=0x12861bac pc=0x74f4fe
cmd/compile/internal/syntax.(*scanner).escape(0x12892010, 0x22, 0x1)
        c:/go/src/cmd/compile/internal/syntax/scanner.go:829 +0x39f fp=0x12861c24 sp=0x12861bd4 pc=0x74f39f
cmd/compile/internal/syntax.(*scanner).stdString(0x12892010)
        c:/go/src/cmd/compile/internal/syntax/scanner.go:680 +0x18e fp=0x12861c48 sp=0x12861c24 pc=0x74e84e
cmd/compile/internal/syntax.(*scanner).next(0x12892010)
        c:/go/src/cmd/compile/internal/syntax/scanner.go:128 +0x2cc fp=0x12861c78 sp=0x12861c48 pc=0x74cddc
cmd/compile/internal/syntax.(*parser).got(...)
        c:/go/src/cmd/compile/internal/syntax/parser.go:183
cmd/compile/internal/syntax.(*parser).want(0x12892000, 0xb)
        c:/go/src/cmd/compile/internal/syntax/parser.go:190 +0xe0 fp=0x12861cbc sp=0x12861c78 pc=0x73b640
cmd/compile/internal/syntax.(*parser).list(0x12892000, 0xb, 0x11, 0xe, 0x12861d3c, 0x4a, 0x0, 0x63bf6c)
        c:/go/src/cmd/compile/internal/syntax/parser.go:473 +0x2d fp=0x12861d1c sp=0x12861cbc pc=0x73c62d
cmd/compile/internal/syntax.(*parser).argList(0x12892000, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/cmd/compile/internal/syntax/parser.go:2218 +0xa6 fp=0x12861d50 sp=0x12861d1c pc=0x7451a6
cmd/compile/internal/syntax.(*parser).pexpr(0x12892000, 0xde5d01, 0x3fffffff, 0x0)
        c:/go/src/cmd/compile/internal/syntax/parser.go:1026 +0x97d fp=0x12861db8 sp=0x12861d50 pc=0x73eedd
cmd/compile/internal/syntax.(*parser).unaryExpr(0x12892000, 0x2200088, 0x32a0b1b0)
        c:/go/src/cmd/compile/internal/syntax/parser.go:792 +0x121 fp=0x12861e04 sp=0x12861db8 pc=0x73da81
cmd/compile/internal/syntax.(*parser).binaryExpr(0x12892000, 0x0, 0x74d33f, 0x12892010)
        c:/go/src/cmd/compile/internal/syntax/parser.go:689 +0x25 fp=0x12861e28 sp=0x12861e04 pc=0x73d805
cmd/compile/internal/syntax.(*parser).expr(...)
        c:/go/src/cmd/compile/internal/syntax/parser.go:682
cmd/compile/internal/syntax.(*parser).exprList(0x12892000, 0x12973301, 0x12b8e510)
        c:/go/src/cmd/compile/internal/syntax/parser.go:2298 +0x2d fp=0x12861e74 sp=0x12861e28 pc=0x74560d
cmd/compile/internal/syntax.(*parser).varDecl(0x12892000, 0x0, 0x12ba01e0, 0x26)
        c:/go/src/cmd/compile/internal/syntax/parser.go:605 +0x113 fp=0x12861e90 sp=0x12861e74 pc=0x73d323
cmd/compile/internal/syntax.(*parser).varDecl-fm(0x0, 0x0, 0x12f04a70)
        c:/go/src/cmd/compile/internal/syntax/parser.go:593 +0x2f fp=0x12861ea4 sp=0x12861e90 pc=0x750a9f
cmd/compile/internal/syntax.(*parser).appendGroup(0x12892000, 0x12ad6000, 0x51, 0x80, 0x12ad3f28, 0x12ad6000, 0x4f, 0x80)
        c:/go/src/cmd/compile/internal/syntax/parser.go:504 +0xe2 fp=0x12861ee4 sp=0x12861ea4 pc=0x73ca12
cmd/compile/internal/syntax.(*parser).fileOrNil(0x12892000, 0x12886000)
        c:/go/src/cmd/compile/internal/syntax/parser.go:417 +0x564 fp=0x12861f34 sp=0x12861ee4 pc=0x73c474
cmd/compile/internal/syntax.Parse(0x12886000, 0xee0b0c, 0x1288e000, 0x1288e008, 0x1288e010, 0x1, 0x0, 0x0, 0x0)
        c:/go/src/cmd/compile/internal/syntax/syntax.go:81 +0xc3 fp=0x12861f64 sp=0x12861f34 pc=0x74fc63
cmd/compile/internal/gc.parseFiles.func1(0x12810880, 0x12967ef0, 0x12866000, 0x5a)
        c:/go/src/cmd/compile/internal/gc/noder.go:53 +0x1bb fp=0x12861fe0 sp=0x12861f64 pc=0xcea5ab
runtime.goexit()
        c:/go/src/runtime/asm_386.s:1315 +0x1 fp=0x12861fe4 sp=0x12861fe0 pc=0x694501
created by cmd/compile/internal/gc.parseFiles
        c:/go/src/cmd/compile/internal/gc/noder.go:40 +0xb9

goroutine 1 [chan receive]:
cmd/compile/internal/gc.parseFiles(0x12864090, 0x4, 0xe, 0x2)
        c:/go/src/cmd/compile/internal/gc/noder.go:59 +0x2b9
cmd/compile/internal/gc.Main(0xde5798)
        c:/go/src/cmd/compile/internal/gc/main.go:578 +0x25d2
main.main()
        c:/go/src/cmd/compile/main.go:52 +0x93

**Comment by tpsmr** [comment]
environment: windows10

**Comment by asticode** [comment]
it seems the machine you're running the bundler on doesn't have enough memory (ram)

**Comment by tpsmr** [comment]
i check task manager the ram is enough when it building..

**Comment by aswallz** [comment]
https://github.com/msepp/go-astilectron-template

Building on a 32bit host most likely won't work due to limited address space. Use 64bit host and cross-compile.
